### ISSUE TITLE
CI: libvirt: kcli cluster creation failing

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1655]
Since around 17:00 UTC yesterday (8/1/24), in both [PR tests](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/7450828468/job/20275796494?pr=1607) and [nightly tests](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/7456619508/job/20288166316) we are getting a failure in the kcli setup:
```
time="2024-01-08T20:03:06Z" level=info msg="Cluster provisioning"
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 5371, in cli
    args.func(args)
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 131, in get_version
    git_version, git_date = get_git_version()
  File "/usr/lib/python3/dist-packages/kvirt/common/__init__.py", line 2112, in get_git_version
    git_version, git_date = open(git_file).read().rstrip().split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
F0108 20:03:08.329146   27874 env.go:369] Setup failure: exit status 1
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e	1.793s
FAIL
```

I had a quick look at https://github.com/karmab/kcli/blame/main/kvirt/common/__init__.py#L2107 and the code doesn't seem to have changed recently, but we'll need to dig in a bit more.

**Comment by karmab** [comment]
hitting the same, let me fix it

**Comment by karmab** [comment]
> Hi @karmab - I wondered if you have seen this elsewhere (it looks like the KCLI CI GHA are still green), or do you think it's something unique to our usage/version?

fixed here https://github.com/karmab/kcli/commit/13db8dfa5e1dcd5cc65f7a140cac4e08d000629e
(somehow github changed the format of their commits)

**Comment by stevenhorsman** [comment]
> fixed here https://github.com/karmab/kcli/commit/13db8dfa5e1dcd5cc65f7a140cac4e08d000629e
(somehow github changed the format of their commits)

Great, thanks for your help as always!

**Comment by stevenhorsman** [comment]
@karmab - we are still seeing this in our CI runs and I'm seeing locally even though it looks like I have picked up the new commit:
```
# curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4694  100  4694    0     0  54588      0 --:--:-- --:--:-- --:--:-- 55223
Installing using deb package
Executing the  setup script for the 'karmab/kcli' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'karmab/kcli' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'karmab/kcli' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Get:1 https://dl.cloudsmith.io/public/karmab/kcli/deb/ubuntu jammy InRelease [4972 B]
Get:2 http://mirrors.adn.networklayer.com/ubuntu jammy InRelease [270 kB]
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease
Get:4 http://mirrors.adn.networklayer.com/ubuntu jammy-updates InRelease [119 kB]
Get:5 http://mirrors.adn.networklayer.com/ubuntu jammy-backports InRelease [109 kB]
Get:6 http://mirrors.adn.networklayer.com/ubuntu jammy-security InRelease [110 kB]
Fetched 613 kB in 3s (199 kB/s)
Reading package lists... Done
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-kcli is already the newest version (99.0-202401091101.13db8df).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
kcli installed
Consider installing completion by following https://kcli.readthedocs.io/#auto-completion
root@sh-podvm-builder-policy-test:~# kcli version
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 5371, in cli
    args.func(args)
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 131, in get_version
    git_version, git_date = get_git_version()
  File "/usr/lib/python3/dist-packages/kvirt/common/__init__.py", line 2112, in get_git_version
    git_version, git_date = open(git_file).read().rstrip().split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
```
Is there anything else I need to do to resolve it?

**Comment by karmab** [comment]
my bad, a similar fix was specifically needed for deb
applied here https://github.com/karmab/kcli/commit/53ab27fc8a5d7e9de7317a5298e4cc3090b91ea0

**Comment by stevenhorsman** [comment]
Cool, working locally now :) Thanks!

**Comment by stevenhorsman** [comment]
The daily libvirt CI is now passing: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/7456619508/job/20301354737, so this is closed as fixed. Thanks to Karim for the excellence response time helping with this!
